# Generated by Django 4.0.5 on 2022-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(null=True, upload_to='images/')),
                ('image_2', models.ImageField(null=True, upload_to='images/')),
                ('animal_name', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
