# Generated by Django 4.0.5 on 2022-11-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal_item_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='animal_item_types/')),
                ('type_name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'animal item types',
            },
        ),
        migrations.CreateModel(
            name='animal_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'animal items',
            },
        ),
        migrations.AlterModelOptions(
            name='animals',
            options={'verbose_name_plural': 'animals'},
        ),
    ]
