data = {
  'animals': [{'id': 6,
               'image_1': '/img/images/dog.jpg',
               'image_2': '/img/images/dog2.jpg',
               'animal_name': 'dog'},
              {'id': 7,
               'image_1': '/img/images/cat.jpg',
               'image_2': '/img/images/cat2.jpg',
               'animal_name': 'cat'},
              {'id': 8,
               'image_1': '/img/images/bird.jpg',
               'image_2': '/img/images/bird2.jpg',
               'animal_name': 'bird'},
              {'id': 9,
               'image_1': '/img/images/bird_hw6QaCv.jpg',
               'image_2': '/img/images/bird2_twFIpBL.jpg',
               'animal_name': 'bird'}],
  'animal_items': [{'id': 5,
                    'item_name': 'food',
                    'connected_to_animal': 6},
                   {'id': 6,
                    'item_name': 'food',
                    'connected_to_animal': 7},
                   {'id': 7,
                    'item_name': 'rise',
                    'connected_to_animal': 8},
                   {'id': 8,
                    'item_name': 'meat',
                    'connected_to_animal': 6},
                   {'id': 9,
                    'item_name': 'bread',
                    'connected_to_animal': 6},
                   {'id': 10,
                    'item_name': 'me',
                    'connected_to_animal': 6}],
  'animal_item_types': [{'id': 6,
                         'image': '/img/images/tropical.jpg',
                         'type_name': 'tropical',
                         'connected_to_animal_items': 5},
                        {'id': 7,
                         'image': '/img/images/tropical_JmYu71y.jpg',
                         'type_name': 'tropically_2',
                         'connected_to_animal_items': 5},
                        {'id': 8,
                         'image': '/img/images/tropical_Q0fejm6.jpg',
                         'type_name': 'tropical_meat',
                         'connected_to_animal_items': 8},
                        {'id': 9,
                         'image': '/img/images/dog_food_dfWuqA8.jpg',
                         'type_name': 'example 123',
                         'connected_to_animal_items': 9},
                        {'id': 10,
                         'image': '/img/images/fish.png',
                         'type_name': 'fishes',
                         'connected_to_animal_items': 10}],
  'animal_foods': [{'id': 2,
                    'image': '/img/images/dog_food.jpg',
                    'food_name': 'example dog food 1',
                    'food_price': '500$ / 1kg',
                    'food_description': 'there are some text for the dog food for an example.',
                    'connected_to_animal_items_types': 6},
                   {'id': 3,
                    'image': '/img/images/dog_food2.jpg',
                    'food_name': 'example dog food 2',
                    'food_price': '500$ / 1kg',
                    'food_description': 'there are some text for the dog food for an exmaple.',
                    'connected_to_animal_items_types': 7},
                   {'id': 4,
                    'image': '/img/images/dog_food_Aj8EVNS.jpg',
                    'food_name': 'example dog food 3',
                    'food_price': '500$ / 1kg',
                    'food_description': 'there are some text for the dog food for an exmaple.',
                    'connected_to_animal_items_types': 8},
                   {'id': 5,
                    'image': '/img/images/dog_food2_jR7LkZG.jpg',
                    'food_name': 'Tropical food for dogs',
                    'food_price': '500$ / 1kg',
                    'food_description': 'there are some text for the dog food for an exmaple.',
                    'connected_to_animal_items_types': 6},
                   {'id': 6,
                    'image': '/img/images/dog_food_ls3wNZj.jpg',
                    'food_name': 'dog food example1',
                    'food_price': '500$ / 1kg',
                    'food_description': 'there are some text for the dog food for an example.',
                    'connected_to_animal_items_types': 6},
                   {'id': 7,
                    'image': '/img/images/dog_food2_C078YmN.jpg',
                    'food_name': 'Tropical food for dogs',
                    'food_price': '500$ / 1kg',
                    'food_description': 'wedjfhvbsd sfvjsdcsnc sdksd k sfd',
                    'connected_to_animal_items_types': 9},
                   {'id': 8,
                    'image': '/img/images/bird_COuYdQa.jpg',
                    'food_name': 'supper fish',
                    'food_price': '500$ / 1kg',
                    'food_description': 'sdbskjs vdf  si v fv dfav dfn vd fvkdf vfdvfdv fev vdk vkd v fdm df',
                    'connected_to_animal_items_types': 10}]}
